-- CreateTable
CREATE TABLE "AaLoad26Monthly" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "january" TEXT,
    "janRemark1" TEXT,
    "janRemark2" TEXT,
    "janRemark3" TEXT,
    "janRemark4" TEXT,
    "janRemark5" TEXT,
    "february" TEXT,
    "febRemark1" TEXT,
    "febRemark2" TEXT,
    "febRemark3" TEXT,
    "febRemark4" TEXT,
    "febRemark5" TEXT,
    "march" TEXT,
    "marRemark1" TEXT,
    "marRemark2" TEXT,
    "marRemark3" TEXT,
    "marRemark4" TEXT,
    "marRemark5" TEXT,
    "april" TEXT,
    "aprRemark1" TEXT,
    "aprRemark2" TEXT,
    "aprRemark3" TEXT,
    "aprRemark4" TEXT,
    "aprRemark5" TEXT,
    "may" TEXT,
    "mayRemark1" TEXT,
    "mayRemark2" TEXT,
    "mayRemark3" TEXT,
    "mayRemark4" TEXT,
    "mayRemark5" TEXT,
    "june" TEXT,
    "junRemark1" TEXT,
    "junRemark2" TEXT,
    "junRemark3" TEXT,
    "junRemark4" TEXT,
    "junRemark5" TEXT,
    "july" TEXT,
    "julRemarks1" TEXT,
    "julRemarks2" TEXT,
    "julRemarks3" TEXT,
    "julRemarks4" TEXT,
    "julRemarks5" TEXT,
    "august" TEXT,
    "augRemarks1" TEXT,
    "augRemarks2" TEXT,
    "augRemarks3" TEXT,
    "augRemarks4" TEXT,
    "augRemarks5" TEXT,
    "september" TEXT,
    "sepRemarks1" TEXT,
    "sepRemarks2" TEXT,
    "sepRemarks3" TEXT,
    "sepRemarks4" TEXT,
    "sepRemarks5" TEXT,
    "october" TEXT,
    "octRemarks1" TEXT,
    "octRemarks2" TEXT,
    "octRemarks3" TEXT,
    "octRemarks4" TEXT,
    "octRemarks5" TEXT,
    "november" TEXT,
    "novRemarks1" TEXT,
    "novRemarks2" TEXT,
    "novRemarks3" TEXT,
    "novRemarks4" TEXT,
    "novRemarks5" TEXT,
    "december" TEXT,
    "decRemarks1" TEXT,
    "decRemarks2" TEXT,
    "decRemarks3" TEXT,
    "decRemarks4" TEXT,
    "decRemarks5" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AaLoad26Monthly_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AaLoad26Monthly_documentId_key" ON "AaLoad26Monthly"("documentId");

-- AddForeignKey
ALTER TABLE "AaLoad26Monthly" ADD CONSTRAINT "AaLoad26Monthly_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "AaDocument"("id") ON DELETE CASCADE ON UPDATE CASCADE;
