const rangeFields = (prefix: string, start: number, end: number, pad = 0) =>
  Array.from({ length: end - start + 1 }, (_, index) => {
    const value = start + index;
    const suffix = pad > 0 ? String(value).padStart(pad, '0') : String(value);
    return `${prefix}${suffix}`;
  });

const column = (field: string, ...indexes: number[]) => ({ field, indexes });

const sequentialColumns = (
  fields: string[],
  startIndex: number,
  skipIndexes: number[] = [],
) => {
  const skipSet = new Set(skipIndexes);
  const mapped: { field: string; indexes: number[] }[] = [];
  let currentIndex = startIndex;

  for (const field of fields) {
    while (skipSet.has(currentIndex)) currentIndex += 1;
    mapped.push(column(field, currentIndex));
    currentIndex += 1;
  }

  return mapped;
};

export interface AaImportDefinition {
  code: string;
  delegate: string;
  sheetNames: string[];
  fields: string[];
  dataStartRow: number;
  columns: { field: string; indexes: number[] }[];
  requiredAll?: string[];
  requiredAny?: string[];
  requiredAnyCount?: number;
  projection: {
    staffField: string;
    subjectFields: string[];
    dateField?: string;
  };
}

export const AA_IMPORT_DEFINITIONS: AaImportDefinition[] = [
  {
    code: 'EDTMS',
    delegate: 'edtmsTrackingRequest',
    sheetNames: ['EDTMS TRACKING REQUEST'],
    fields: [
      'edtmsNumber',
      'staffRequesting',
      'dateCreated',
      'subject',
      'uploadedBy',
      'uploadDate',
      'remarks',
      'dateForwarded',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'edtmsNumber',
        'staffRequesting',
        'dateCreated',
        'subject',
        'uploadedBy',
        'uploadDate',
        'remarks',
        'dateForwarded',
      ],
      0,
    ),
    requiredAny: ['edtmsNumber', 'staffRequesting', 'subject'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffRequesting',
      subjectFields: ['subject'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'CVS',
    delegate: 'cvsTracking',
    sheetNames: ['CVS (COA, SWA REPORT, ALL CVS D'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'documentTitle',
      'dateSubmitted',
      'remarks1',
      'remarks2',
      'remarks3',
      'remarks4',
      'remarks5',
      'remarks6',
    ],
    dataStartRow: 2,
    columns: [
      column('drnTrackingNo', 0),
      column('staffName', 1),
      column('documentTitle', 2, 3),
      column('dateSubmitted', 4),
      column('remarks1', 5),
      column('remarks2', 6),
      column('remarks3', 7),
      column('remarks4', 8),
      column('remarks5', 9),
      column('remarks6', 10),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle'],
      dateField: 'dateSubmitted',
    },
  },
  {
    code: 'BDM',
    delegate: 'bdmTracking',
    sheetNames: ['BDM (ALL THINGS UPDATING)'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'subject',
      'dateCreated',
      'remarks1',
      'remarks2',
      'remarks3',
      'remarks4',
      'remarks5',
      'remarks6',
      'remarks7',
    ],
    dataStartRow: 2,
    columns: [
      column('drnTrackingNo', 0),
      column('staffName', 1),
      column('subject', 2),
      column('dateCreated', 3),
      column('remarks1', 5),
      column('remarks2', 6),
      column('remarks3', 7),
      column('remarks4', 8),
      column('remarks5', 9),
      column('remarks6', 10),
      column('remarks7', 11),
    ],
    requiredAll: ['drnTrackingNo', 'staffName', 'subject'],
    projection: {
      staffField: 'staffName',
      subjectFields: ['subject'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'GRS',
    delegate: 'grsTracking',
    sheetNames: ['GRS (CSMF, RETRO, REKLAMO ETC)'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'referredToGrsRpmo',
      'documentTitle',
      'dateCreated',
      'dateSubmittedJnt',
      ...rangeFields('remarks', 1, 17),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'drnTrackingNo',
          'staffName',
          'referredToGrsRpmo',
          'documentTitle',
          'dateCreated',
          'dateSubmittedJnt',
        ],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 17), 6),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle', 'referredToGrsRpmo'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'MNE',
    delegate: 'mneTracking',
    sheetNames: ['MNE (SWDIHAF ACTIVITY DOCUMENTA'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'activityDocumentation',
      'documentTitle',
      'dateCreated',
      ...rangeFields('remarks', 1, 7),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'drnTrackingNo',
          'staffName',
          'activityDocumentation',
          'documentTitle',
          'dateCreated',
        ],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 7), 5),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle', 'activityDocumentation'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'OOLEVEL',
    delegate: 'ooLevel',
    sheetNames: ['OO LEVEL'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'documentTitle',
      'dateCreated',
      ...rangeFields('remarks', 1, 7),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        ['drnTrackingNo', 'staffName', 'documentTitle', 'dateCreated'],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 7), 4),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'OO8',
    delegate: 'oo8IncomingFiles',
    sheetNames: ['OO8 INCOMING FILES (AA ONLY)'],
    fields: [
      'drnTrackingNo',
      'edtms',
      'fromParty',
      'addressedTo',
      'documentTitle',
      ...rangeFields('remarks', 1, 5),
    ],
    dataStartRow: 1,
    columns: [
      column('drnTrackingNo', 0),
      column('edtms', 1),
      column('fromParty', 2),
      column('addressedTo', 3),
      column('documentTitle', 4),
      column('remarks1', 5),
      column('remarks2', 6),
      column('remarks3', 7),
      column('remarks4', 8),
      column('remarks5', 9),
    ],
    requiredAny: ['edtms', 'fromParty', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'fromParty',
      subjectFields: ['documentTitle', 'addressedTo'],
    },
  },
  {
    code: 'TRAINING',
    delegate: 'trainingFeedbacks',
    sheetNames: ['TRAINING FEEDBACKS'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'documentTitle',
      'dateCreated',
      'dateSubmittedJnt',
      ...rangeFields('remarks', 1, 6),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'drnTrackingNo',
          'staffName',
          'documentTitle',
          'dateCreated',
          'dateSubmittedJnt',
        ],
        0,
      ),
      column('remarks1', 5),
      column('remarks2', 6),
      column('remarks3', 7),
      column('remarks4', 8),
      column('remarks5', 10),
      column('remarks6', 11),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'TRAVEL',
    delegate: 'travelRequest',
    sheetNames: ['TRAVEL REQUEST'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      ...rangeFields('coveredDates', 1, 22, 2),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        ['employeeName', 'employmentStatus', 'areaOfAssignment'],
        0,
      ),
      ...sequentialColumns(rangeFields('coveredDates', 1, 22, 2), 3),
    ],
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'MRBTOF',
    delegate: 'mrbTofMonitoring',
    sheetNames: ['MRB (TOF MONITORING)'],
    fields: [
      'ooLevelDrnNumber',
      'dateForwardedToMrb',
      'assignedCitylink',
      'mrbInCharge',
      'tofNumber',
      'requestTitle',
      'dateForwardedToCgu',
      'remarks',
    ],
    dataStartRow: 1,
    columns: sequentialColumns(
      [
        'ooLevelDrnNumber',
        'dateForwardedToMrb',
        'assignedCitylink',
        'mrbInCharge',
        'tofNumber',
        'requestTitle',
        'dateForwardedToCgu',
        'remarks',
      ],
      0,
    ),
    requiredAny: ['ooLevelDrnNumber', 'mrbInCharge', 'requestTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'mrbInCharge',
      subjectFields: ['requestTitle', 'assignedCitylink'],
      dateField: 'dateForwardedToMrb',
    },
  },
  {
    code: 'COAWTR26',
    delegate: 'coaWTr2026',
    sheetNames: ['COA W TR 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'january',
      'janRemarksMe1',
      'janRemarksMe2',
      'february',
      'febRemarksMe',
      'march',
      'marRemarksMe',
      'april',
      'aprRemarksMe',
      'may',
      'mayRemarksMe',
      'june',
      'junRemarksMe',
      'july',
      'julRemarksMe',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'january',
        'janRemarksMe1',
        'janRemarksMe2',
        'february',
        'febRemarksMe',
        'march',
        'marRemarksMe',
        'april',
        'aprRemarksMe',
        'may',
        'mayRemarksMe',
        'june',
        'junRemarksMe',
        'july',
        'julRemarksMe',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'COCOT',
    delegate: 'filedForCocot',
    sheetNames: ['FILED FOR COCOT (AA ONLY)'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'janRemarks1',
      'janRemarks2',
      'janRemarks3',
      'february',
      ...rangeFields('febRemarks', 1, 8),
      'april',
      'may',
      'mayRemarks1',
      'mayRemarks2',
      'june',
      'junRemarks1',
      'junRemarks2',
      'july',
      'julRemarks1',
      'julRemarks2',
      'julRemarks3',
      'august',
      'augRemarks',
      'september',
      'sepRemarks1',
      'sepRemarks2',
      'sepRemarks3',
      'october',
      'octRemarks1',
      'octRemarks2',
      'octRemarks3',
      'november',
      'novRemarks1',
      'novRemarks2',
    ],
    dataStartRow: 2,
    columns: [
      column('employeeName', 0),
      column('employmentStatus', 1),
      column('areaOfAssignment', 2),
      column('janRemarks1', 3),
      column('janRemarks2', 4),
      column('janRemarks3', 5),
      column('february', 6),
      column('febRemarks1', 7),
      column('febRemarks2', 8),
      column('febRemarks3', 9),
      column('febRemarks4', 10),
      column('febRemarks5', 11),
      column('febRemarks6', 12),
      column('febRemarks7', 13),
      column('febRemarks8', 14),
      column('april', 18),
      column('may', 21),
      column('mayRemarks1', 22),
      column('mayRemarks2', 23),
      column('june', 24),
      column('junRemarks1', 25),
      column('junRemarks2', 26),
      column('july', 27),
      column('julRemarks1', 28),
      column('julRemarks2', 29),
      column('julRemarks3', 30),
      column('august', 31),
      column('augRemarks', 32),
      column('september', 33),
      column('sepRemarks1', 34),
      column('sepRemarks2', 35),
      column('sepRemarks3', 36),
      column('october', 37),
      column('octRemarks1', 38),
      column('octRemarks2', 39),
      column('octRemarks3', 40),
      column('november', 41),
      column('novRemarks1', 42),
      column('novRemarks2', 43),
    ],
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'SUCCESS',
    delegate: 'successStories',
    sheetNames: ['SUCCESS STORIES'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'documentTitle',
      'dateCreated',
      'dateUploadedDrive',
      'storyType',
      'kwentoPangarap',
      'kwentoPagtataya',
      'kwentoPagtataguyod',
      'kwentoPagbabago',
      'googleLinkFolder',
    ],
    dataStartRow: 3,
    columns: [
      column('drnTrackingNo', 0),
      column('staffName', 1),
      column('documentTitle', 2),
      column('dateCreated', 3),
      column('dateUploadedDrive', 4),
      column('storyType'),
      column('kwentoPangarap', 7, 23),
      column('kwentoPagtataya', 8, 24),
      column('kwentoPagtataguyod', 9, 25),
      column('kwentoPagbabago', 10, 26),
      column('googleLinkFolder', 6, 7, 8, 9, 10, 12, 22, 23, 24, 25, 26),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle', 'storyType'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'DTR26',
    delegate: 'dtr2026',
    sheetNames: ['DTR 2026'],
    fields: [
      'number',
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'december2025',
      'decRemarks1',
      'decRemarks2',
      'january',
      'janRemarks1',
      'janRemarks2',
      'february',
      'febRemarks',
      'march',
      'marRemarks',
      'april',
      'aprRemarks',
      'may',
      'mayRemarks1',
      'mayRemarks2',
      'june',
      'junRemarks1',
      'junRemarks2',
      'july',
      'julRemarks1',
      'julRemarks2',
      'julRemarks3',
      'august',
      'augRemarks',
      'september',
      'sepRemarks1',
      'sepRemarks2',
      'sepRemarks3',
      'october',
      'octRemarks1',
      'octRemarks2',
      'octRemarks3',
      'november',
      'novRemarks1',
      'novRemarks2',
    ],
    dataStartRow: 2,
    columns: [
      column('number', 0),
      column('employeeName', 1),
      column('employmentStatus', 2),
      column('areaOfAssignment', 3),
      column('december2025', 4),
      column('decRemarks1', 5),
      column('decRemarks2', 6),
      column('january', 7),
      column('janRemarks1', 8),
      column('janRemarks2', 9),
      column('february', 10),
      column('febRemarks', 11),
      column('march', 12),
      column('marRemarks', 13),
      column('april', 14),
      column('aprRemarks', 15),
      column('may', 22),
      column('mayRemarks1', 23),
      column('mayRemarks2', 24),
      column('june', 25),
      column('junRemarks1', 26),
      column('junRemarks2', 27),
      column('july', 28),
      column('julRemarks1', 29),
      column('julRemarks2', 30),
      column('julRemarks3', 31),
      column('august', 32),
      column('augRemarks', 33),
      column('september', 34),
      column('sepRemarks1', 35),
      column('sepRemarks2', 36),
      column('sepRemarks3', 37),
      column('october', 38),
      column('octRemarks1', 39),
      column('octRemarks2', 40),
      column('octRemarks3', 41),
      column('november', 42),
      column('novRemarks1', 43),
      column('novRemarks2', 44),
    ],
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'HAZARD26',
    delegate: 'hazard2026',
    sheetNames: ['HAZARD 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'january',
      'janRemarks1',
      'janRemarks2',
      'february',
      'febRemarks1',
      'febRemarks2',
      'march',
      'marRemarks1',
      'marRemarks2',
      'april',
      'aprRemarks1',
      'aprRemarks2',
      'may',
      'mayRemarks1',
      'mayRemarks2',
      'june',
      'junRemarks1',
      'junRemarks2',
      'july',
      'julRemarks1',
      'julRemarks2',
      'august',
      'augRemarks1',
      'augRemarks2',
      'september',
      'sepRemarks1',
      'sepRemarks2',
      'october',
      'octRemarks1',
      'octRemarks2',
      'november',
      'novRemarks1',
      'novRemarks2',
      'december',
      'decRemarks1',
      'decRemarks2',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'january',
        'janRemarks1',
        'janRemarks2',
        'february',
        'febRemarks1',
        'febRemarks2',
        'march',
        'marRemarks1',
        'marRemarks2',
        'april',
        'aprRemarks1',
        'aprRemarks2',
        'may',
        'mayRemarks1',
        'mayRemarks2',
        'june',
        'junRemarks1',
        'junRemarks2',
        'july',
        'julRemarks1',
        'julRemarks2',
        'august',
        'augRemarks1',
        'augRemarks2',
        'september',
        'sepRemarks1',
        'sepRemarks2',
        'october',
        'octRemarks1',
        'octRemarks2',
        'november',
        'novRemarks1',
        'novRemarks2',
        'december',
        'decRemarks1',
        'decRemarks2',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'TEV26',
    delegate: 'tev2026',
    sheetNames: ['TEV 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'january',
      'janRemarks1',
      'janRemarks2',
      'janRemarks3',
      'february',
      'febRemarks1',
      'febRemarks2',
      'march',
      'marRemarks1',
      'marRemarks2',
      'april',
      'aprRemarks1',
      'aprRemarks2',
      'aprilDup',
      'aprDupRemarks1',
      'aprDupRemarks2',
      'may',
      'mayRemarks1',
      'mayRemarks2',
      'june',
      'junRemarks1',
      'junRemarks2',
      'july',
      'julRemarks1',
      'julRemarks2',
      'august',
      'augRemarks1',
      'augRemarks2',
      'september',
      'sepRemarks1',
      'sepRemarks2',
      'october',
      'octRemarks1',
      'octRemarks2',
      'november',
      'novRemarks1',
      'novRemarks2',
      'december',
      'decRemarks1',
      'decRemarks2',
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'employeeName',
          'employmentStatus',
          'areaOfAssignment',
          'january',
          'janRemarks1',
          'janRemarks2',
          'janRemarks3',
          'february',
          'febRemarks1',
          'febRemarks2',
          'march',
          'marRemarks1',
          'marRemarks2',
          'april',
          'aprRemarks1',
          'aprRemarks2',
          'aprilDup',
          'aprDupRemarks1',
          'aprDupRemarks2',
        ],
        0,
      ),
      column('may', 20),
      column('mayRemarks1', 21),
      column('mayRemarks2', 22),
      column('june', 23),
      column('junRemarks1', 24),
      column('junRemarks2', 25),
      column('july', 26),
      column('julRemarks1', 27),
      column('julRemarks2', 28),
      column('august', 29),
      column('augRemarks1', 30),
      column('augRemarks2', 31),
      column('september', 32),
      column('sepRemarks1', 33),
      column('sepRemarks2', 34),
      column('october', 35),
      column('octRemarks1', 36),
      column('octRemarks2', 37),
      column('november', 38),
      column('novRemarks1', 39),
      column('novRemarks2', 40),
      column('december', 41),
      column('decRemarks1', 42),
      column('decRemarks2', 43),
    ],
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'LOAD26',
    delegate: 'loadAllowance2026',
    sheetNames: ['LOAD ALLOWANCE 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'january',
      'janRemark1',
      'janRemark2',
      'janRemark3',
      'janRemark4',
      'janRemark5',
      'february',
      'febRemark1',
      'febRemark2',
      'febRemark3',
      'febRemark4',
      'febRemark5',
      'march',
      'marRemark1',
      'marRemark2',
      'marRemark3',
      'marRemark4',
      'marRemark5',
      'april',
      'aprRemark1',
      'aprRemark2',
      'aprRemark3',
      'aprRemark4',
      'aprRemark5',
      'may',
      'mayRemark1',
      'mayRemark2',
      'mayRemark3',
      'mayRemark4',
      'mayRemark5',
      'june',
      'junRemark1',
      'junRemark2',
      'junRemark3',
      'junRemark4',
      'junRemark5',
      'july',
      'julRemarks1',
      'julRemarks2',
      'julRemarks3',
      'julRemarks4',
      'julRemarks5',
      'august',
      'augRemarks1',
      'augRemarks2',
      'augRemarks3',
      'augRemarks4',
      'augRemarks5',
      'september',
      'sepRemarks1',
      'sepRemarks2',
      'sepRemarks3',
      'sepRemarks4',
      'sepRemarks5',
      'october',
      'octRemarks1',
      'octRemarks2',
      'octRemarks3',
      'octRemarks4',
      'octRemarks5',
      'november',
      'novRemarks1',
      'novRemarks2',
      'novRemarks3',
      'novRemarks4',
      'novRemarks5',
      'december',
      'decRemarks1',
      'decRemarks2',
      'decRemarks3',
      'decRemarks4',
      'decRemarks5',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'january',
        'janRemark1',
        'janRemark2',
        'janRemark3',
        'janRemark4',
        'janRemark5',
        'february',
        'febRemark1',
        'febRemark2',
        'febRemark3',
        'febRemark4',
        'febRemark5',
        'march',
        'marRemark1',
        'marRemark2',
        'marRemark3',
        'marRemark4',
        'marRemark5',
        'april',
        'aprRemark1',
        'aprRemark2',
        'aprRemark3',
        'aprRemark4',
        'aprRemark5',
        'may',
        'mayRemark1',
        'mayRemark2',
        'mayRemark3',
        'mayRemark4',
        'mayRemark5',
        'june',
        'junRemark1',
        'junRemark2',
        'junRemark3',
        'junRemark4',
        'junRemark5',
        'july',
        'julRemarks1',
        'julRemarks2',
        'julRemarks3',
        'julRemarks4',
        'julRemarks5',
        'august',
        'augRemarks1',
        'augRemarks2',
        'augRemarks3',
        'augRemarks4',
        'augRemarks5',
        'september',
        'sepRemarks1',
        'sepRemarks2',
        'sepRemarks3',
        'sepRemarks4',
        'sepRemarks5',
        'october',
        'octRemarks1',
        'octRemarks2',
        'octRemarks3',
        'octRemarks4',
        'octRemarks5',
        'november',
        'novRemarks1',
        'novRemarks2',
        'novRemarks3',
        'novRemarks4',
        'novRemarks5',
        'december',
        'decRemarks1',
        'decRemarks2',
        'decRemarks3',
        'decRemarks4',
        'decRemarks5',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'MAGNA26',
    delegate: 'magnaCarta2026',
    sheetNames: ['MAGNA CARTA - 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'january',
      'janRemarks1',
      'janRemarks2',
      'february',
      'febRemarks1',
      'febRemarks2',
      'march',
      'marRemarks1',
      'marRemarks2',
      'april',
      'aprRemarks',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'january',
        'janRemarks1',
        'janRemarks2',
        'february',
        'febRemarks1',
        'febRemarks2',
        'march',
        'marRemarks1',
        'marRemarks2',
        'april',
        'aprRemarks',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'LEAVE',
    delegate: 'leaveForms',
    sheetNames: ['LEAVE FORMS (AA ONLY)'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      ...rangeFields('remarks', 1, 20, 2),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        ['employeeName', 'employmentStatus', 'areaOfAssignment'],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 20, 2), 3),
    ],
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'CVSDD',
    delegate: 'cvsDropdown',
    sheetNames: ['CVS DROPDOWN'],
    fields: ['documentType', 'yesNoValue'],
    dataStartRow: 1,
    columns: [column('documentType', 0), column('yesNoValue', 2)],
    requiredAny: ['documentType', 'yesNoValue'],
    requiredAnyCount: 1,
    projection: {
      staffField: 'documentType',
      subjectFields: ['yesNoValue'],
    },
  },
  {
    code: 'IPCRF25',
    delegate: 'ipcrf2ndSem2025',
    sheetNames: ['IPCRF 2ND SEM 2025'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'remarks1',
      'remarks2',
      'remarks3',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'remarks1',
        'remarks2',
        'remarks3',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'SALN26',
    delegate: 'saln2026',
    sheetNames: ['SALN 2026'],
    fields: [
      'employeeName',
      'employmentStatus',
      'areaOfAssignment',
      'remarks1',
      'remarks2',
      'remarks3',
    ],
    dataStartRow: 2,
    columns: sequentialColumns(
      [
        'employeeName',
        'employmentStatus',
        'areaOfAssignment',
        'remarks1',
        'remarks2',
        'remarks3',
      ],
      0,
    ),
    requiredAll: ['employeeName', 'employmentStatus'],
    projection: {
      staffField: 'employeeName',
      subjectFields: ['areaOfAssignment', 'employmentStatus'],
    },
  },
  {
    code: 'ACONLY',
    delegate: 'acOnly',
    sheetNames: ['AC ONLY'],
    fields: [
      'drnTrackingNo',
      'staffName',
      'documentTitle',
      'dateCreated',
      'dateSubmittedJnt',
      ...rangeFields('remarks', 1, 7),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'drnTrackingNo',
          'staffName',
          'documentTitle',
          'dateCreated',
          'dateSubmittedJnt',
        ],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 7), 5),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle'],
      dateField: 'dateCreated',
    },
  },
  {
    code: 'SWOIII',
    delegate: 'swoiiiOnly',
    sheetNames: ['SWOIII ONLY'],
    fields: [
      'drnTrackingNo',
      'edtms',
      'staffName',
      'documentTitle',
      'dateCreated',
      'dateSubmittedJnt',
      ...rangeFields('remarks', 1, 7),
    ],
    dataStartRow: 2,
    columns: [
      ...sequentialColumns(
        [
          'drnTrackingNo',
          'edtms',
          'staffName',
          'documentTitle',
          'dateCreated',
          'dateSubmittedJnt',
        ],
        0,
      ),
      ...sequentialColumns(rangeFields('remarks', 1, 7), 6),
    ],
    requiredAny: ['drnTrackingNo', 'staffName', 'documentTitle'],
    requiredAnyCount: 2,
    projection: {
      staffField: 'staffName',
      subjectFields: ['documentTitle', 'edtms'],
      dateField: 'dateCreated',
    },
  },
];

export const AA_IMPORT_DEFINITIONS_BY_CODE = new Map(
  AA_IMPORT_DEFINITIONS.map((definition) => [definition.code, definition]),
);

const normalizeSheetName = (sheetName: string) =>
  sheetName.trim().replace(/\s+/g, ' ').toUpperCase();

export const AA_IMPORT_DEFINITIONS_BY_SHEET_NAME = new Map(
  AA_IMPORT_DEFINITIONS.flatMap((definition) =>
    definition.sheetNames.map(
      (sheetName) => [normalizeSheetName(sheetName), definition] as const,
    ),
  ),
);
