export interface AaModuleCatalogEntry {
  code: string;
  name: string;
  prefix: string;
  description: string | null;
  isMonthly?: boolean;
  colStaff?: string | null;
  colSubject?: string | null;
  colActivity?: string | null;
}

export const AA_MODULE_CATALOG: AaModuleCatalogEntry[] = [
  {
    code: 'EDTMS',
    name: 'EDTMS Tracking Request',
    prefix: 'EDTMS',
    description:
      'Tracks EDTMS requests, requesting staff, and forwarding remarks.',
    colStaff: 'STAFF REQUESTING',
    colSubject: 'SUBJECT',
  },
  {
    code: 'CVS',
    name: 'CVS Tracking',
    prefix: 'CVS',
    description: 'Tracks CVS documents, staff names, and multi-step remarks.',
    colStaff: 'Name of the Staff',
    colSubject: 'Title of Documents',
  },
  {
    code: 'BDM',
    name: 'BDM Tracking',
    prefix: 'BDM',
    description: 'Tracks BDM document requests and remark history.',
    colStaff: 'NAME OF STAFF',
    colSubject: 'SUBJECT',
  },
  {
    code: 'GRS',
    name: 'GRS Tracking',
    prefix: 'GRS',
    description:
      'Tracks GRS and RPMO document referrals with detailed remarks.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
    colActivity: 'Referred to GRS/RPMO',
  },
  {
    code: 'MNE',
    name: 'MNE Tracking',
    prefix: 'MNE',
    description:
      'Tracks monitoring and evaluation documents and activity documentation.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
    colActivity: 'ACTIVITY DOCUMENTATION',
  },
  {
    code: 'OOLEVEL',
    name: 'OO Level',
    prefix: 'OOLEVEL',
    description: 'Tracks OO level documents and remarks.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
  },
  {
    code: 'OO8',
    name: 'OO8 Incoming Files',
    prefix: 'OO8',
    description:
      'Tracks incoming files, source parties, and addressed recipients.',
    colStaff: 'FROM',
    colSubject: 'Title of Documents',
    colActivity: 'ADDRESSED TO',
  },
  {
    code: 'TRAINING',
    name: 'Training Feedbacks',
    prefix: 'TRAINING',
    description: 'Tracks training feedback submissions and remark history.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
  },
  {
    code: 'TRAVEL',
    name: 'Travel Request',
    prefix: 'TRAVEL',
    description: 'Tracks travel request records by employee and covered dates.',
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'MRBTOF',
    name: 'MRB TOF Monitoring',
    prefix: 'MRBTOF',
    description: 'Tracks TOF monitoring from OO level through CGU forwarding.',
    colStaff: 'MRB IN-CHARGE',
    colSubject: 'TITLE OF REQUEST',
    colActivity: 'ASSIGNED CITYLINK',
  },
  {
    code: 'COAWTR',
    name: 'COA WTR',
    prefix: 'COAWTR',
    description: 'Tracks COA WTR requirements by employee.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'COCOT',
    name: 'Filed for COCOT',
    prefix: 'COCOT',
    description: 'Tracks filed COCOT requirements and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'EMPLOYEE STATUS',
  },
  {
    code: 'SUCCESS',
    name: 'Success Stories',
    prefix: 'SUCCESS',
    description: 'Tracks success story submissions and Google Drive links.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
  },
  {
    code: 'DTR',
    name: 'DTR',
    prefix: 'DTR',
    description: 'Tracks DTR compliance and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'EMPLOYEE STATUS',
  },
  {
    code: 'HAZARD',
    name: 'Hazard',
    prefix: 'HAZARD',
    description: 'Tracks hazard-related submissions and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'TEV',
    name: 'TEV',
    prefix: 'TEV',
    description: 'Tracks TEV submissions and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'LOAD',
    name: 'Load Allowance',
    prefix: 'LOAD',
    description: 'Tracks load allowance requirements and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'EMPLOYEE STATUS',
  },
  {
    code: 'MAGNA',
    name: 'Magna Carta',
    prefix: 'MAGNA',
    description: 'Tracks Magna Carta requirements and monthly remarks.',
    isMonthly: true,
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'LEAVE',
    name: 'Leave Forms',
    prefix: 'LEAVE',
    description: 'Tracks leave form submissions and remarks.',
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'CVSDD',
    name: 'CVS Dropdown',
    prefix: 'CVSDD',
    description: 'Tracks CVS dropdown document configuration values.',
    colStaff: 'ENDORSEMENT',
    colSubject: 'YES / NO',
  },
  {
    code: 'IPCRF',
    name: 'IPCRF 2nd Sem',
    prefix: 'IPCRF',
    description: 'Tracks second semester IPCRF submissions.',
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'SALN',
    name: 'SALN',
    prefix: 'SALN',
    description: 'Tracks SALN requirements and remarks.',
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'IDP',
    name: 'IDP',
    prefix: 'IDP',
    description: 'Tracks IDP submissions and remarks.',
    colStaff: 'NAME OF EMPLOYEE',
    colSubject: 'AREA OF ASSIGNMENT',
    colActivity: 'STATUS OF EMPLOYMENT',
  },
  {
    code: 'ACONLY',
    name: 'AC Only',
    prefix: 'ACONLY',
    description: 'Tracks AC-only documents and submitted remarks.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
  },
  {
    code: 'SWOIII',
    name: 'SWOIII Only',
    prefix: 'SWOIII',
    description: 'Tracks SWOIII-only documents, EDTMS references, and remarks.',
    colStaff: 'Name of Staff',
    colSubject: 'Title of Documents',
    colActivity: 'EDTMS',
  },
];
